# Default values for webServer-broker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Image to use
image: local/web-server:v0.1.0
# ImagePullPolicy; valid values are "IfNotPresent", "Never", and "Always"
imagePullPolicy: Always
# Whether the broker should also log to stderr instead of to files only
alsoLogToStdErr: true
# Certificate details to use for TLS. Leave blank to not use TLS
tls:
  # base-64 encoded PEM data for the TLS certificate
  cert:
  # base-64 encoded PEM data for the private key matching the certificate
  key: