apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: testbroker
spec:
  # url: <ip>:<port> -> ip is you localIP where docker container with SB is running
  url: http://testbroker-service.testbroker.svc.cluster.local:12345/
  authInfo:
    basic:
      secretRef:
        namespace: default
        name: test-secret
