apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testbroker-deployment
  namespace: testbroker
spec:
  selector:
    matchLabels:
      app: testbroker
  replicas: 1
  template:
    metadata:
      labels:
        app: testbroker
    spec:
      containers:
      - name: testbroker
        image: local/run-broker:v0.1.0
        ports:
        - containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: testbroker-service
  namespace: testbroker
spec:
  selector:
    app: testbroker
  ports:
  - name: http
    port: 5050
    targetPort: 5000
